"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # 2. Call the tool to "open the vault"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%+%!%)p1s=okt4lx6jqj^i18-@s+ul4@*2ni8vr@5+vg@m0*em'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',  # Changed by Mark
    'students', ## Added By Saim Munshi: student application
    'teachers', ## Added By Saim Munshi: teacher application
    'courses', # Added by Mark

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS is a LIST. You can have multiple paths here.
        'DIRS': [
            os.path.join(BASE_DIR, 'users/main/templates'),
            # ADD THIS LINE to tell Django to also look in your features folder
            os.path.join(BASE_DIR, 'students/features'),
        ],
        'APP_DIRS': True, # Keep this True. It's not hurting anything.
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#Added by Sam: MongoDB conFiguration code takes uri from the env file
# --- DATABASE SECTION ---
DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'MentoringAppDB',
        'HOST': os.getenv('MONGO_URL'),
    }
}


# DMedia-Storage
#Added by Saim: this so Django knows to use the URL from your .env
#Added by Saim: Storage Setup tells django to use cloudinary for storing media
CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': os.getenv('CLOUDINARY_URL')
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
#Added By Sam MongoDb does not auto incrment numbers so the buttom code is to help
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
SILENCED_SYSTEM_CHECKS = ['mongodb.E001']

"""
#Orginal code for Sqllite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

#Added By Saim Munshi: combines based folder to path to the feature directories 
STATICFILES_DIRS =[

    ###### Users App Connection#########
    #Added By Saim Munshi: This is to connect the main base folder to the user Application features in static directory.  
     os.path.join(BASE_DIR, 'users/main/static'),

    ###### Student App Connection#########
    #Added By Saim Munshi: This is to connect the main base folder to the Student Application features in static directory.  
    os.path.join(BASE_DIR, 'students/features/calendar/static'), # Updated spelling
    os.path.join(BASE_DIR, 'students/features/dashboard/static'), # Updated: changed Home to dashboard
    os.path.join(BASE_DIR, 'students/features/Mentors/static'),
    os.path.join(BASE_DIR, 'students/features/Setting/static'),
    os.path.join(BASE_DIR, 'students/features/Skills/static'),
    os.path.join(BASE_DIR, 'students/features/Tasks/static'),
    os.path.join(BASE_DIR, 'students/features/feedback/static'), # Added by Mark: Non-empty pages

    ###### Teacher App Connection#########
    #Added By Saim Munshi: This is to connect the main base folder to the Teacher Application features in static directory.  
    os.path.join(BASE_DIR, 'teachers/features/Calendar/static'), 
    os.path.join(BASE_DIR, 'teachers/features/Home/static'),
    os.path.join(BASE_DIR, 'teachers/features/Create_Task/static'), 
    os.path.join(BASE_DIR, 'teachers/features/My_Student/static'), 
    os.path.join(BASE_DIR, 'teachers/features/Meeting/static'),
    os.path.join(BASE_DIR, 'teachers/features/Setting/static'),
]

# Added by Mark: Testing login sessions and user permissions
AUTH_USER_MODEL = 'users.CustomUser' 
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
