"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # 2. Call the tool to "open the vault"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%+%!%)p1s=okt4lx6jqj^i18-@s+ul4@*2ni8vr@5+vg@m0*em'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'teachers',
    'students',
    'courses',  # Added by Mark
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # Users App Connection Logic
            os.path.join(BASE_DIR, 'users/MainHome/templates'),
            os.path.join(BASE_DIR, 'users/TeacherRegistration/templates'),
            os.path.join(BASE_DIR, 'users/StudentRegistration/templates'),
            os.path.join(BASE_DIR, 'users/SignInPage/templates'),

            # Teacher App templates 
            os.path.join(BASE_DIR, 'teachers/BaseTeacher/templates'),
            os.path.join(BASE_DIR, 'teachers/features'),
            os.path.join(BASE_DIR, 'teachers/features/Progress/templates'),  # added by win516

            # Student App templates
            os.path.join(BASE_DIR, 'students/BaseStudent/templates'),
            os.path.join(BASE_DIR, 'students/features'),
            os.path.join(BASE_DIR, 'students/features/Progress/templates'),  # added by win516

            """
            BASE_DIR / 'users' / 'TeacherRegistration' / 'templates',
            BASE_DIR / 'users' / 'StudentRegistration' / 'templates',
            BASE_DIR / 'users' / 'SignInPage' / 'templates',
            BASE_DIR / 'users' / 'MainHome' / 'templates',

            #Student App Connection Logic
            BASE_DIR / 'students' / 'BaseStudent'/ 'templates',
            BASE_DIR / 'students' / 'features' / 'Courses' / 'templates',
            BASE_DIR / 'students' / 'features' / 'StudentHomePage' / 'templates',

            #Teacher App Connection Logic
            BASE_DIR / 'teachers' / 'BaseTeacher'/ 'templates',
            BASE_DIR / 'teachers' / 'features' / 'TeacherHomePage' / 'templates',
            BASE_DIR / 'teachers' / 'features' / 'Create_Task' / 'templates',
            """
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'teachers.context_processors.notifications_processor',  # Added by Saim
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Added by Mark: Testing login sessions and user permissions
# Edited by Mark: changed order because of race condition?
AUTH_USER_MODEL = 'users.CustomUser'

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'MentoringAppDB',
        'HOST': os.getenv('MONGO_URL'),
        # DO NOT put DEFAULT_AUTO_FIELD here!
    }
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# DMedia-Storage
# Added by Saim: this so Django knows to use the URL from your .env
# Added by Saim: Storage Setup tells django to use cloudinary for storing media
CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': os.getenv('CLOUDINARY_URL')
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Added By Sam: MongoDB does not auto increment numbers so the below code is to help
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
SILENCED_SYSTEM_CHECKS = ['mongodb.E001']

"""
#Original code for Sqlite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Where to go after a successful manual login if no 'next' parameter is present
###LOGIN_REDIRECT_URL = 'teacher_home' 

# Added by Mark: This should fix any @login_required redirects and new logout
LOGIN_URL = 'signin_page_view'
LOGOUT_REDIRECT_URL = "/"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Added By Saim Munshi: combines base folder to path to the feature directories
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

STATICFILES_DIRS = [

    # Added by Mark: For site favicon
    os.path.join(BASE_DIR, 'static'),

    ###### Users App Connection #########
    os.path.join(BASE_DIR, 'users/SignInPage/static'),
    os.path.join(BASE_DIR, 'users/MainHome/static'),
    os.path.join(BASE_DIR, 'users/TeacherRegistration/static'),
    os.path.join(BASE_DIR, 'users/StudentRegistration/static'),

    ###### Student App Connection #########
    os.path.join(BASE_DIR, 'students/BaseStudent/static'),
    os.path.join(BASE_DIR, 'students/features/Calendar/static'),
    os.path.join(BASE_DIR, 'students/features/StudentHomePage/static'),
    os.path.join(BASE_DIR, 'students/features/Mentors/static'),
    os.path.join(BASE_DIR, 'students/features/Setting/static'),
    os.path.join(BASE_DIR, 'students/features/Progress/static'),
    os.path.join(BASE_DIR, 'students/features/Courses/static'),

    os.path.join(BASE_DIR, 'students/features/tasks/static'),

    ###### Teacher App Connection#########
    #Added By Saim Munshi: This is to connect the main base folder to the Teacher Application features in static directory. 
    os.path.join(BASE_DIR, 'teachers/BaseTeacher/static'),
    os.path.join(BASE_DIR, 'teachers/features/Calendar/static'),
    os.path.join(BASE_DIR, 'teachers/features/teacher-courses/static'),  # Added by Mark
    os.path.join(BASE_DIR, 'teachers/features/TeacherHomePage/static'),
    os.path.join(BASE_DIR, 'teachers/features/tasks/static'),  # Added by Mark
    os.path.join(BASE_DIR, 'teachers/features/My_Student/static'),
    os.path.join(BASE_DIR, 'teachers/features/Setting/static'),
    os.path.join(BASE_DIR, 'teachers/BaseTeacher/static'),
]

from django.core.servers.basehttp import WSGIServer