# Generated by Django 5.2.11 on 2026-03-02 22:06

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_teacher',
            },
        ),
    ]
