# Generated by Django 5.2.3 on 2026-03-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
