# Generated by Django 5.2.3 on 2026-03-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_delete_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
