# Generated by Django 5.2.11 on 2026-03-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='students.student'),
        ),
    ]
