# Generated by Django 5.2.3 on 2026-03-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_testtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTask',
        ),
    ]
