# Generated by Django 5.2.3 on 2026-03-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_testtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_archived_for_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
