# Generated by Django 5.2.3 on 2026-03-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_feedback_is_archived_for_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfeedback',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
